language: node_js #设置语言

node_js: "10.16.3" #设置语言版本

cache:
  directories:
    - node_modules #缓存依赖

# S: Build Lifecycle
install:
  - npm install -g hexo-cli
  - npm install

script:
  - hexo clean
  - hexo g

after_script:
    - git clone https://${GH_REF} .deploy_git
    - cd .deploy_git
    - git checkout master
    - cd ../
    - mv .deploy_git/.git/ ./public/
    - cd ./public
    - git config user.name "yourname"
    - git config user.email "your email"
    - git add .
    - git commit -m "Travis CI Auto Builder"
    - git push --force --quiet "https://travis-ci@${GH_REF}" master:master
  

# 只有指定的分支提交时才会运行脚本
branches:
  only:
    - blog

env:
    global:
        - GH_REF: github.com/lyz05/lyz05.github.io.git #设置GH_REF，注意更改yourname