language: node_js #设置语言

node_js: "10.16.3" #设置语言版本

cache:
  directories:
    - node_modules #缓存依赖

# S: Build Lifecycle
install:
  - npm install -g hexo-cli
  - npm install

script:
  - hexo clean
  - hexo g
  - hexo deploy
  

# 只有指定的分支提交时才会运行脚本
branches:
  only:
    - blog