#language_switcher: true

footer:
    since: 2015
    icon:
      animated: true

tag_icon: true
mobile_layout_economy: true
  
creative_commons:
    sidebar: true
    post: false

scheme: Gemini

darkmode: true

menu:
  home: / || fa fa-home
  tags: /tags/ || fa fa-tags
  categories: /categories/ || fa fa-th
  archives: /archives/ || fa fa-archive
  file: https://static.home999.cc/ || fa fa-folder
  note: /note/ || fa fa-clipboard
  books: /books/ || fa fa-book
  movie: /movies/ || fa fa-film
  about: /about/ || fa fa-user

menu_settings:
  icons: true
  badges: true

avatar:
  url: /images/avatar.webp
  rounded: true
  
social:
  GitHub: https://github.com/lyz05 || fab fa-github
  E-Mail: mailto:liuyuanzhe0515@gmail.com || fa fa-envelope
  知乎: http://www.zhihu.com/people/liu-yuan-zhe-16 || iconfont icon-douban
  豆瓣: http://www.douban.com/people/140286755/ || iconfont icon-zhihu

social_icons:
  icons_only: true

links_settings:
  layout: inline
  
links:
  IceCream: https://blog.xuegaogg.com
  levan: http://sub.tbetbe.com/
  佩奇kakkoii: http://blog.d999k.cn/
  Mchobby: https://mchobbylong.github.io/
  Rat's: https://www.moerats.com/
  Byvoid: https://www.byvoid.com/
  hzwer: http://hzwer.com/
  
back2top:
  scrollpercent: true
  
math:
  per_page: true
  mathjax:
    enable: true
    
valine:
  enable: true
  appId: XIvfHitkQpcIdYONge8baBBR-gzGzoHsz
  appKey: nV8vEtsT9WYR9pGPCxEXyqWl
  visitor: true
  serverURLs: https://xivfhitk.lc-cn-n1-shared.com
  
local_search:
  enable: true
  
pdf:
  enable: true
  
codeblock:
  copy_button:
    enable: true

motion:
  enable: false
  async: true
  transition:
    post_block: fadeIn
    post_header: 
    post_body: 
    coll_header: 
    sidebar: fadeInUp
    
nprogress:
  enable: true
  
quicklink:
  enable: false
  
custom_file_path:
  style: source/_data/styles.styl