# Remove unnecessary files after hexo generate.
minify: true

scheme: Gemini

darkmode: true
  
creative_commons:
    sidebar: true
    post: false

menu:
  home: / || fa fa-home
  tags: /tags/ || fa fa-tags
  categories: /categories/ || fa fa-th
  archives: /archives/ || fa fa-archive
  file: https://gd.home999.cc/ || fa fa-folder
  note: /note/ || fa fa-clipboard
  books: /books/ || fa fa-book
  movie: /movies/ || fa fa-film
  about: /about/ || fa fa-user

menu_settings:
  icons: true
  badges: true

avatar:
  url: /images/avatar.webp
  rounded: true
  
social:
  GitHub: https://github.com/lyz05 || fab fa-github
  E-Mail: mailto:liuyuanzhe0515@gmail.com || fa fa-envelope
  知乎: http://www.zhihu.com/people/liu-yuan-zhe-16 || iconfont icon-douban
  豆瓣: http://www.douban.com/people/140286755/ || iconfont icon-zhihu

social_icons:
  icons_only: true

links_settings:
  layout: inline
  
links:
  IceCream: https://blog.xuegaogg.com
  levan: http://sub.tbetbe.com/
  佩奇kakkoii: http://blog.d999k.cn/
  Mchobby: https://mchobbylong.github.io/
  Rat's: https://www.moerats.com/
  Byvoid: https://www.byvoid.com/
  hzwer: http://hzwer.com/
  VsKendo: https://blog.nowcoder.net/vskendo
  
back2top:
  scrollpercent: true
  
math:
  per_page: true
  mathjax:
    enable: true
    
valine:
  enable: true
  appId: IOO0v6UWzOQE94hPLrgXiQhg-9Nh9j0Va
  appKey: vBfyrsgGJnqg8qG3PD4MglR8
  visitor: true
  serverURLs: https://ioo0v6uw.lc-cn-e1-shared.com
  
local_search:
  enable: true
  
pdf:
  enable: true
  
codeblock:
  copy_button:
    enable: true

motion:
  enable: false
  async: true
  transition:
    post_block: fadeIn
    post_header: 
    post_body: 
    coll_header: 
    sidebar: fadeInUp
    
nprogress:
  enable: true
  
quicklink:
  enable: false
  
custom_file_path:
  style: source/_data/styles.styl

footer:
    since: 2015
    icon:
      animated: true

tag_icon: true
mobile_layout_economy: true

github_banner:
  enable: true
  permalink: https://github.com/lyz05

# It's recommended to use the same version as in `_vendors.yml` to avoid potential problems.
# Remember to use the https protocol of CDN links when you enable https on your site.
vendors:
  # The CDN provider of NexT internal scripts.
  # Available values: local | jsdelivr | unpkg | cdnjs
  # Warning: If you are using the latest master branch of NexT, please set `internal: local`
  internal: jsdelivr
  # The default CDN provider of third-party plugins.
  # Available values: local | jsdelivr | unpkg | cdnjs
  # Dependencies for `plugins: local`: https://github.com/next-theme/plugins
  plugins: jsdelivr