name: Hexo Deploy

on:
  push:
    branches:
      - blog

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Shanghai
          
      - name: Checkout source
        uses: actions/checkout@v2
          
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Setup Hexo
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_PRI }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "294068487@qq.com"
          git config --global user.name "lyz05"
          npm install hexo-cli -g
          npm install
          hexo clean
          hexo douban -bm

      - name: Deploy To Github Pages
        run: |
          hexo g
          hexo deploy
          
      - name: Setup ossutil
        uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: "oss-cn-hongkong.aliyuncs.com"
          access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.ACCESS_KEY_SECRET }}
    
      - name: Deply To OSS
        run: |
          hexo g --config _config.yml,_config.lang.yml
          ossutil cp -ru public oss://lyz05blog/ 

      - name: Sending message
        uses: yakumioto/serverchan-action@v1
        with:
          key: ${{ secrets.sckey }}
          text: 博客部署成功
          desp: 博客部署成功